


services:
  db:
    image: postgres:15
    container_name: chat-postgres-test
    restart: always
    env_file:
      - .env.test
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # To store data even if container stops
      - ./init-db:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
